"""
Alcohols list :
    -vodka
    -rum
    -gin
    -whiskey
    -cachaca
    -coffee liqueur
    -triple sec
    -bourbon
    -tequila
    -absinthe
    -dry vermouth
    -sweet red vermouth
    -campari
    -creme de mure
    -cherry heering
    -benedictine
    -chambord
    -kahlua
    -strawberry liqueur
    -creme de cacao
    -pisco
    -champagne
    -creme de banane
    -peach schnapps
    -prosecco
    -cognac
    -passoa
    -black raspberry liqueur
    -brandy
"""
# Loop through the ingredients
# change Ingredients -> only rum (ex) or do if ex: rum in ingredients
cocktails = [
    {"id": 0,
    "alcohols": ["rum"],
    "name": "Mojito",
    "ingredients": ["50 ml White Rum", "8 Mint leaves", "12 1/2 ml Sugar Syrup", "25 ml Lime Juice", "2 Mint sprigs"],
    "description": "Add the white rum to a highball glass. Add 8 – 10 mint leaves and sugar syrup and lime juice.Muddle with bar spoon. Add crushed ice and a splash of soda. Mix drink down with bar spoon. Taste. Top up with more crushed ice. Slap 2 mint sprigs to release essence and put into drink. Add small splash of soda and straw."},
    {"id": 1,
    "alcohols": ["gin", "dry vermouth"],
    "name": "Martini",
    "ingredients": ["50 ml Gin", "10 ml Dry Vermouth", "Lemon twist"],
    "description": "Chill martini glass with soda water and ice. Fill mixing glass to top with ice. Add the dry vermouth to the mixing glass, giving a small stir to coat the ice with the vermouth. Drain out glass, leaving just the coating on the ice. Add the gin to the mixing glass. Stir for 15 seconds, always making sure that the glass is full to the brim with ice. Taste. Fine strain into chilled martini glass. Zest with lemon peel and add twist unto drink."},
    {"id": 2,
    "name": "Daiquiri",
    "alcohols": ["rum"],
    "ingredients": ["50 ml White Rum", "1 1/2 bar spoons Sugar", "25 ml Lime Juice", "Lime slice"],
    "description": "Chill coupe glass with soda water. Add sugar to mixing tin and then add white rum and lime juice. Add a little cracked ice to the bottom then fill the rest of the tin with ice. Shake for 10 – 15 seconds, taste and then fine strain into coupe glass. Garnish glass with lime slice."},
    {"id": 3,
    "alcohols": ["whiskey"],
    "name": "Old Fashioned",
    "ingredients": ["50 ml Bourbon", "2 dashes Angostura Bitters", "1 dash Orange Bitters", "1 bar spoon Sugar", "Orange peel"],
    "description": "Begin by chilling rocks glass with ice and soda water. Add 1 bar spoon of sugar into mixing glass. Add 2 dashes of Angostura bitters and 1 dash of orange bitters. Muddle to break down the sugar into a paste. Add the bourbon into a mixing glass and fill the rest of the mixing glass with ice. Stir with bar spoon for at least 20 seconds. Top up with ice and taste. Put ice into rocks glass and strain the drink into the glass. Zest the glass with orange peel and add twist into drink."},
    {"id": 4,
    "alcohols": ["vodka", "triple sec"],
    "name": "Cosmopolitan",
    "ingredients": ["37 1/2 ml Citrus Vodka", " 12 1/2 ml Triple Sec", "30 ml Cranberry Juice", "1/2 squeezed lemon", "12 1/2 ml Sugar Syrup"],
    "description": "Chill coupe glass with soda water. Add all ingredients to mixing tin with ice. Shake for 10 to 15 seconds. Fine strain into the chilled coupe glass. Flame an orange peel and place in drink as garnish."},
    {"id": 5,
    "alcohols": ["cachaca"],
    "name": "Caipirinha",
    "ingredients": ["50 ml Cachaca", "1/2 Lime", "1 teaspoon Brown Sugar", "Lime Wedge"],
    "description": "Cut 1/2 lime into 1/8 ths and add half of these to Rocks glass. Add teaspoon of brown sugar and muddle the ingredients. Add the rest of the lime and continue to muddle, to dissolve the sugar. Add the Cachaca and then add crushed ice on top. Stir to continue to dissolve the sugar. Add more crushed ice and continue to stir. Top up with crushed ice and garnish with lime wedge."},
    {"id": 6,
    "alcohols": ["vodka", "coffe liqueur"],
    "name": "White Russian",
    "ingredients": ["37 1/2 ml Vodka", "25 ml Coffee Liqueur", "15 ml Cream", "15 ml Milk", "Chocolate Powder", "Coffee Bean"],
    "description": "For the perfect White Russian recipe add coffee liqueur to an old-fashioned glass. Add other ingredients to mixing tin and fill to brim with ice. Shake for 10 -15 seconds. Single strain the ingredients over the ice and coffee liqueur. Sprinkle with chocolate powder and garnish with coffee bean."},
    {"id": 7,
    "alcohols": ["rum"],
    "name": "Pina Colada",
    "ingredients": ["50 ml White Rum", "100 ml Pineapple Juice", "25 ml Coconut Cream", " 25 ml Cream", "Pineapple Slice", "pinch of Salt"],
    "description" : "Chill highball glass. Add all ingredients to mixing tin and fill with ice. Shake vigorously for 10 – 15 seconds. Fill highball glass with fresh ice and strain drink into glass. Garnish with pineapple slice, add straw and serve."},
    {"id": 8,
    "alcohols": ["gin", "sweet red vermouth", "campari"],
    "name": "Negroni",
    "ingredients": ["25 ml Gin", "25 ml Sweet Red Vermouth", "25 ml Campari", "Orange Peel"],
    "description": "Chill rocks glass with ice and soda water.Fill mixing tin to rim with ice and add in all ingredients. Stir with bar spoon for 20 seconds. Taste. Add fresh ice to rocks glass and strain the drink into glass. Zest glass with orange peel, twist and place in drink."},
    {"id": 9,
    "alcohols": ["gin","creme de mure"],
    "name": "Bramble",
    "ingredients": ["50 ml Gin", "10 ml Crème de Mure", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "Blackberry"],
    "description": "Add all ingredients (except creme de mure) into mixing glass. Fill  mixing glass with cubed ice and fill rocks glass with crushed ice. Shake for 10 seconds. Strain mixture into glass and top up with crushed ice. Pour creme de mure over drink using bar spoon. Garnish with 2 lemon slices and blackberry."},
    {"id": 10,
    "alcohols": ["tequila"],
    "name": "Margarita",
    "ingredients": ["37 1/2 ml Tequila", "12 1/2 ml Triple Sec", "25 ml Lime Juice", "12 1/2 ml Simple Syrup", "salt"],
    "description": "Begin by half soaking rim of coupe glass with lime juice and then dab in salt. Use cloth to tidy up the glass for presentation. Add all ingredients into mixing tin with 2 ice cubes and dry shake for 10 seconds. Fill mixing tin with ice and shake for a further 10 – 15 seconds. Fine strain into the pre-prepared coupe glass."},
    {"id": 11,
    "alcohols": ["rum"],
    "name": "Dark and Stormy",
    "ingredients": ["50 ml Dark Rum", "4 Lime quarters", "1 1/2 bar spoons Brown Sugar", "splash Ginger Beer", "Lime wedge"],
    "description": "Chill highball glass with soda water. Place 4 lime quarters into mixing tin and add 1 1/2 bar spoons of brown sugar. Muddle ingredients. Add 50 ml of dark rum. Fill mixing tin with ice and shake hard for 10 – 15 seconds. Taste. Add fresh ice to the highball glass and single strain drink over the ice. Top up with ginger beer and add straw. Garnish with lime wedge."},
    {"id": 12,
    "alcohols": ["rum"],
    "name": "Cuba Libre",
    "ingredients": ["50 ml Anejo Rum", "8 Lime wedges", "100 ml Cola", "Lime wedge"],
    "description": "Add rum into rocks glass and squeeze the lime wedges over the top. Give quick churn with bar spoon and top up with ice. Fill to brim with cola and add in lime wedge as garnish."},
    {"id": 13,
    "alcohols": ["whiskey", "absinthe"],
    "name": "Sazerac",
    "ingredients": ["50 ml Rye Whiskey", "5 ml Absinthe", " 3 dashes of Peychauds Bitters", "Sugar Cube", "Lemon Peel"],
    "description": "One rocks glass is packed with ice and water to chill the glass. In a second rocks glass, muddle the sugar cube with the bitters. Add the rye to this mixture. Stir to combine. Empty the ice from the first glass. Pour the absinthe into the glass and swirl to coat the sides of the glass. Any excess absinthe is discarded. Pour the rye/sugar/bitters mixture into the coated glass. Twist a lemon peel over the glass and rub the rim of the glass with the peel. The peel can be discarded or placed in the cocktail."},
    {"id": 14,
    "alcohols": ["vodka", "sweet vermouth"],
    "name": "Bloody Mary",
    "ingredients": ["37 1/2 ml Peppered Vodka", "15 ml Sweet Vermouth", "35 ml Tomato Juice", "splash Red Wine", "6 splashes Worcestershire sauce", "10 dashes Tobasco sauce", " 25 ml Lemon Juice", "10 dashes Salt", "10 dashes Pepper", "3 Cucumber slices"],
    "description": "Chill a highball glass with ice. Pour all the ingredients, apart from red wine, into mixing tin and add ice. Roll the mixing tin for 15 seconds. Taste. Add ice to glass and single strain the drink into a glass. Add  a splash of red wine and a dash of pepper. Garnish with 3 cucumber slices."},
    {"id": 15,
    "alcohols": ["bourbon", "sweet vermouth", "dry vermouth"],
    "name": "Manhattan",
    "ingredients": ["50 ml Bourbon", "10 ml Sweet Vermouth", "10 ml Dry Vermouth", "2 dashes Angostura Bitters", "Orange peel"],
    "description": "Chill cocktail glass with ice and soda. Fill a mixing glass with ice and then add all ingredients. Using a bar spoon, stir the drink for approximately 20 seconds. When stirring, always ensure the glass is topped up with ice.Taste and then strain into the chilled cocktail glass, serving straight up. Zest the drink and glass with the orange peel and then twist and place in glass."},
    {"id": 16,
    "alcohols": ["gin", "vodka", "tequila", "rum", "triple sec"],
    "name": "Long Island Iced Tea",
    "ingredients": ["15 ml Gin", "15 ml Vodka", "15 ml Tequila", "15 ml White Rum", "15 ml Triple Sec", "25 ml Lemon Juice", "30 ml Gomme syrup", "splash of Cola"],
    "description": "Begin by chilling highball glass with soda water and ice. Add all ingredients (except the cola) into a mixing tin. Add ice to tin and shake for 10 seconds. Add fresh ice to highball glass and add splash of cola. Strain the ingredients into glass. Add lemon slice and straw."},
    {"id": 17,
    "alcohols": ["rum", "triple sec"],
    "name": "Mai-Tai",
    "ingredients": ["20 ml Dark Rum", "20 ml Light Rum", "splash Demerara 20 ml Triple Sec", "20 ml Lime Juice", "10 ml Orgeat Syrup", "Mint sprig", "Orange wedge"],
    "description": "Add all ingredients into mixing tin. Fill mixing tin with cubed ice. Shake very hard for 10 seconds to achieve desired dilution. Fill goblet style glass with crushed ice and strain mixture into glass. Add a short straw, mint and a splash of demerara rum."},
    {"id": 18,
    "alcohols": ["amaretto"],
    "name": "Amaretto Sour",
    "ingredients": ["50 ml Amaretto", "25 ml Lemon Juice", "1/2 ml Simple Syrup", "dash Egg-White", "dash Angostura Bitters", "Lemon Zest"],
    "description": "Add all ingredients into mixing glass. Dry shake for 5 seconds. Add cubed ice into shaker and shake for 10 seconds. Fill rocks glass with cubed ice and strain mixture into glass. Garnish with lemon zest, spreading the oils across the glass."},
    {"id": 19,
    "alcohols": ["gin", "cherry heering", "benedictine"],
    "name": "Singapore Sling",
    "ingredients": ["37 1/2 ml Gin", "12 1/2 ml Cherry Heering", "12 1/2 ml Benedictine", "25 ml Lemon Juice", "2 dashes Orange Bitters", "2 dashes Angostura Bitters", "dash Soda Water", "Lemon slice"],
    "description": "Chill highball glass with soda water. Add all ingredients into mixing tin and fill with ice. Shake hard for 10 seconds. Taste. Top up the highball glass with ice and single strain the drink into glass. Top up with soda water, add straw and garnish with lemon slice."},
    {"id": 20,
    "alcohols": ["vodka", "chambord"],
    "name": "French Martini",
    "ingredients": ["25 ml Vodka", "25 ml Chambord", "75 ml Pineapple Juice", "3 Raspberries for Garnish"],
    "description": "Pour the ingredients into a cocktail shaker with ice cubes, shake well, Strain into a chilled cocktail glass, arnish with 3 Raspberries."},
    {"id": 21,
    "alcohols": ["vodka", "kahlua"],
    "name": "Espresso Martini",
    "ingredients": ["37 1/2 ml Vanilla Vodka", "12 1/2 ml Kahlúa", "Double Espresso", "12 1/2 ml Sugar Syrup", "3 Coffee Beans"],
    "description": "Add all ingredients into a Boston cocktail shaker and fill with ice. Shake hard for up to 30 seconds to achieve the desired consistency of the drink. Double strain the contents of the shaker into a chilled martini glass. Garnish with 3 coffee beans."},
    {"id": 22,
    "alcohols": ["rum", "strawberry liqueur"],
    "name": "Strawberry Daiquiri",
    "ingredients": ["37 1/2 ml Bacardi Rum", "12 1/2 ml Strawberry Liqueur", "25 ml Lime Juice", "12 1/2 ml Sugar Syrup", "1 Strawberry"],
    "description": "Add all ingredients into a Boston Shaker and fill with ice. Shake for about 15 seconds and then strain into a chilled martini glass. Garnish with a strawberry."},
    {"id": 23,
    "alcohols": ["vodka"],
    "name": "Moscow Mule",
    "ingredients": ["37 1/2 ml Vodka", "25 ml Lime juice", "12 1/2 ml Sugar Syrup", "splash Ginger Beer"],
    "description": "Chill highball glass with ice and soda. Add all ingredients apart from ginger beer into mixing tin. Fill tin with ice and shake for about 10 – 15 seconds. Fill glass with fresh ice. Add splash of ginger beer to bottom of glass and strain drink into glass. Add straw and garnish with lime wedge."},
    {"id": 24,
    "alcohols": ["gin", "sweet vermouth"],
    "name": "Clover Club",
    "ingredients": ["37 1/2 ml Caorunn Gin", "37 1/2 ml Lemon Juice", "20 ml Sweet Vermouth", "20 ml Raspberry Syrup", "1 Egg White"],
    "description": "Pour the ingredients into cocktail shaker and dry shake for 5 seconds. Add ice to the shaker and shake hard for a further 15 seconds. Single strain into a coupe glass and serve."},
    {"id": 25,
    "alcohols": ["bourbon"],
    "name": "Mint Julep",
    "ingredients": ["50 ml Knob Creek Bourbon", "bar spoon Granulated Sugar", "8 Mint leaves", "Mint sprigs"],
    "description": "Add a bar spoon of granulated sugar into glass. Place 8 mint leaves into the glass and add 15 ml of Bourbon. Gently muddle contents of the glass. Add a further 35 ml of bourbon and then fill glass half way with crushed ice. Churn for 15 seconds and taste. Fill the remainder of the glass to the top with crushed ice. Slap mint sprigs to release flavour and add to top of drink. Place straw into drink next to mint sprigs."},
    {"id": 26,
    "alcohols": ["whiskey"],
    "name": "John Collins",
    "ingredients": ["50 ml Bourbon Whiskey", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "splash of Soda Water", "Maraschino Cherry"],
    "description": "Mix the Bourbon, lemon juice and sugar syrup in a Boston shaker with ice. Single strain into a high ball glass filled with ice. Top up with soda water. Garnish with maraschino cherry."},
    {"id": 27,
    "alcohols": ["gin"],
    "name": "Gin Sour",
    "ingredients": ["50 ml Gin", "25 ml Lemon Juice", "12 1/2 ml Simple Syrup", "Splash Egg-White"],
    "description": "Begin by chilling glass with ice and soda water. Add the gin, simple syrup, lemon juice and egg white to a mixing tin and dry shake for 10 seconds. Add ice to the mixing tin and shake for a further 10 seconds. Give a quick taste. Fill glass with ice and strain drink into glass. Squeeze some lemon zest over drink and add lemon twist into glass."},
    {"id": 28,
    "alcohols": ["vodka", "triple sec"],
    "name": "Appletini",
    "ingredients": ["40 ml Vodka", "15 ml Apple Schapps", "15 ml Triple Sec", "Apple Slice"],
    "description": "Mix in a shaker and then pour into a chilled cocktail glass. Garnish with apple slice and serve."},
    {"id": 29,
    "alcohols": ["gin", "triple sec"],
    "name": "White Lady",
    "ingredients": ["50 ml Gin", "25 ml Triple Sec", "25ml Lemon Juice", "Lemon Rind"],
    "description": "Mix the ingredients in a shaker which is half full of ice. Strain and serve in a sugar-rimmed glass. Garnish with a strip of lemon rind."},
    {"id": 30,
    "alcohols": ["vodka", "coffee liqueur"],
    "name": "Black Russian",
    "ingredients": ["45 ml Vodka", "25 ml Coffee Liqueur"],
    "description": "Add vodka and coffee liqueur to rocks glass. Fill glass with ice. Stir for 5 seconds with bar spoon. Top up with ice and serve."},
    {"id": 31,
    "alcohols": ["brandy", "creme de cacao"],
    "name": "Brandy Alexander",
    "ingredients": ["37 1/2 ml Brandy", "20 ml Crème de Cacao", "50 ml Milk", "Grated Nutmeg"],
    "description": "Add all ingredients into a mixing glass. Fill glass with cubed ice and shake for 10 seconds. Double strain mixture into cocktail glass. Garnish with dusting of nutmeg."},
    {"id": 32,
    "alcohols": ["gin"],
    "name": "French 75",
    "ingredients": ["37 1/2 ml Caorunn Gin", "splash Champagne", "10 ml Sugar Syrup", "15 ml Lemon Juice"],
    "description": "Chill Champagne flute with soda water. Add sugar syrup, gin and lemon juice into a mixing tin. Top up with ice and then shake for 10 seconds. Fine strain contents of mixing tin into Champagne flute and top up with Champagne."},
    {"id": 33,
    "alcohols": ["rum"],
    "name": "Navy Grog",
    "ingredients": ["50 ml Dark Rum", "25 ml Light Rum", "20 ml Lime Juice", "50 ml Pink Grapefruit Juice", "12 1/2 ml Runny Honey", "Top-Up Soda"],
    "description": "Add all ingredients in mixing tin and top-up with ice. Shake hard for 10 seconds. Fill glass with crushed ice and pout in mixture. Garnish with a cherry."},
    {"id": 34,
    "alcohols":["whiskey", "wiskey liqueur"],
    "name": "Rusty Nail",
    "ingredients": ["50 ml Scotch Whisky", "25 ml Whiskey Liqueur"],
    "description": "Add whiskey and drambuie to rocks glass. Half fill with ice and give a quick stir. Add a couple more ice cubes. Serve."},
    {"id": 35,
    "alcohols":["pisco"],
    "name": "Pisco Sour",
    "ingredients": ["50 ml Pisco", "12 1/2 ml Simple Syrup", "25 ml Lime Juice", "splash Egg White", "Lime wedge"],
    "description": "Chill rocks glass with soda and ice. Add all ingredients to mixing tin and dry shake for 10 seconds. Fill mixing tin with ice and then shake vigorously for a further 10 seconds. Add fresh ice to the rocks glass. Single strain into glass over ice and garnish with lime wedge."},
    {"id": 36,
    "alcohols":["champagne"],
    "name": "Bucks Fizz",
    "ingredients": ["50 ml Orange Juice", "100 ml Champagne"],
    "description": "Pour 50 ml of orange juice into Champagne flute. Using a bar spoon, float Champagne on top. Lightly stir to combine."},
    {"id": 37,
    "alcohols":["rum", "creme de banane", "creme de mure"],
    "name": "Rum Runner",
    "ingredients": ["37 1/2 ml Aged Rum", "20 ml White Rum", "12 1/2 ml Creme de Banane", "12 1/2 ml Creme de Mure", "15 ml Pineapple Juice", "15 ml Orange Juice", "Orange slice"],
    "description": "Chill down rocks glass with ice and soda. Add all ingredients into mixing tin. Add ice to mixing tin and shake hard for 10 seconds. Add fresh ice into rocks glass and strain the drink into the glass. Garnish with orange slice."},
    {"id": 38,
    "alcohols":["rum", "orange liqueur", "dry vermouth"],
    "name": "El Presidente",
    "ingredients": ["50 ml Aged Rum", "12 1/2 ml Orange Liqueur", "10 ml Dry Vermouth", "splash Grenadine", "Orange Peel"],
    "description": "Begin by chilling coupe glass with ice and soda. Add ice to mixing glass and add all ingredients. Stir sown the drink for 20 seconds, using a bar spoon. When mixing ensure the glass is kept full to the brim with ice. Strain the drink into the chilled coupe glass and serve straight up. Garnish with orange peel twist."},
    {"id": 39,
    "alcohols":["peach schnapps", "vodka"],
    "name": "WooWoo",
    "ingredients": ["37 1/2 ml Peach Schnapps", "37 1/2 ml Vodka", "90 ml Cranberry Juice"],
    "description": "Pour all ingredients into a highball glass over ice cubes, stir with bar spoon for 15 seconds and serve."},
    {"id": 40,
    "alcohols":["champagne", "creme de cassis"],
    "name": "Kir Royale",
    "ingredients": ["80 ml Champagne", "20 ml Crème de Cassis"],
    "description": "Add the crème de cassis to the bottom of a chilled Champagne flute, then top up with Champagne, using a bar spoon to float the champagne on top. Stir gently to combine."},
    {"id": 41,
    "alcohols":["prosecco"],
    "name": "Bellini",
    "ingredients": ["100 ml Prosecco", "50 ml Peach puree", "4 dashes Peach Bitters"],
    "description": "Add 4 dashes of peach bitters into chilled champagne flute. Add peach puree and top up with Prosecco."},
    {"id": 42,
    "alcohols":["vodka", "orange liqueur"],
    "name": "Lemon Drop Martini",
    "ingredients": ["37 1/2 ml Vodka", "12 1/2 ml Orange Liqueur", "12 1/2 ml Sugar Syrup", "25 ml Lemon Juice", "Lemon Twist", "Sugar"],
    "description": "Add all ingredients into a Boston shaker and fill with ice. Shake well then double strain into a chilled martini glass that has been rimmed with sugar. Garnish with the twisted lemon peel."},
    {"id": 43,
    "alcohols":["gin"],
    "name": "Pink Gin",
    "ingredients": ["25 ml Gin", "3 dashes Angostura Bitters"],
    "description": "Coat the sides of a chilled martini glass with Angostura bitters, add chilled gin and serve."},
    {"id": 44,
    "alcohols":["vodka"],
    "name": "Salty Dog",
    "ingredients": ["50 ml Vodka", "20 ml Dry Sherry", "37 1/2 ml Grapefruit Juice", "15 ml Sugar Syrup", "Salt", "Grapefruit Zest"],
    "description": "Prep a margarita glass by dipping half the rim in salt. Add all the ingredients to a cocktail shaker and shake with ice for about 10 seconds. Double strain into the salted glass. Zest the top of the drink with some grapefruit."},
    {"id": 45,
    "alcohols":["coffee liqueur", "irish cream liqueur", "triple sec"],
    "name": "B-52",
    "ingredients": ["10 ml Coffee Liqueur", "10 ml Irish Cream Liqueur", "10 ml Triple Sec"],
    "description": "Layer ingredients into a shot glass. Serve with a stirrer."},
    {"id": 46,
    "alcohols":["rum"],
    "name": "Painkiller",
    "ingredients": ["50 ml Dark Rum", "25 ml Coconut Cream", "100 ml Pineapple Juice", "25 ml Orange Juice", "Orange Wheel"],
    "description": "Add all ingredients into a mixing tin and top-up with cubed ice. Shake hard for 10 seconds. Fill a tall glass with crushed ice and strain mixture into glass. Garnish with orange wheel."},
    {"id": 47,
    "alcohols":["vodka"],
    "name": "Screwdriver",
    "ingredients": ["50 ml Vodka", "100 ml freshly squeezed Orange Juice", "Lime wedge"],
    "description": "Add vodka into highball glass and fill up to the top with ice. Squeeze a lime wedge into drink and rim glass. Top up with freshly squeezed orange juice. Add straw and serve."},
    {"id": 48,
    "alcohols":["cognac", "amaretto"],
    "name": "French Connection",
    "ingredients": ["25 ml Cognac", "25 ml Amaretto"],
    "description": "Pour ingredients into a snifter glass with ice cubes. Stir gently with a bar spoon."},
    {"id": 49,
    "alcohols":["tequila"],
    "name": "Paloma",
    "ingredients": ["50 ml Tequila", "27 1/2 ml Pink Grapefruit Juice", "20 ml Sugar Syrup", "10 ml Lime Juice", "Pink Grapefruit wedge"],
    "description": "Chill highball glass. Add all ingredients into highball and fill to brim with ice. Stir with bar spoon for 10 seconds. Top up with fresh ice and top up with soda. Add straw and garnish with wedge of pink grapefruit."},
    {"id": 50,
    "alcohols":["gin"],
    "name": "Royal Hawaiian",
    "ingredients": ["37 1/2 ml Gin", "25 ml Pineapple Juice", "25 ml Lemon Juice", "5 ml Orgeat Syrup", "12 1/2 ml Simple Syrup", "Lemon Slice", "Mint Leaves"],
    "description": "Add all the ingredients to the mixing tin and fill with cubed ice. Shake thoroughly for 10 seconds. Fill rocks glass half full with crushed ice and strain ingredients into glass. Garnish with lemon slice and fresh mint."},
    {"id": 51,
    "alcohols":["tequila"],
    "name": "Tommy`s Margarita",
    "ingredients": ["50 ml Tequila", "25 ml Lime Juice", "12 1/2 ml", "Lemon Slices", "Blackberry"],
    "description": "Add all 3 ingredients to a mixing tin. Add ice to mixing tin and rocks glass. Shake for 10 – 15 seconds and then strain into rocks glass. Garnish with 2 lemon slices and blackberry."},
    {"id": 52,
    "alcohols":["vodka"],
    "name": "Sea Breeze",
    "ingredients": ["50 ml Vodka", "50 ml Cranberry Juice", "37 1/2 ml Grapefruit Juice", "Lime Slice"],
    "description": "Pour cranberry into glass first filled with ice. Dry shake the vodka with grapefruit and layer on top of the cranberry. Garnish with lime wedge."},
    {"id": 53,
    "alcohols":["gin"],
    "name": "Ramos Gin Fizz",
    "ingredients": ["50 ml Gin", "25 ml Double Cream", "1 Egg White", "15 ml Lemon Juice", "15 ml Lime Juice", "20 ml Sugar Syrup", "4 drops Orange Flower Water", "splash of Soda Water", "Lemon Zest Twist"],
    "description": "Add all ingredients into a shaker. Dry shake for 5 seconds. Add ice to the shaker and shake for up to 4 minutes to achieve the consistency desired for this drink. Add a dash of soda water to the bottom of a Collins glass and double strain the contents of the shaker into the glass. Zest the drink with a lemon twist and add into drink."},
    {"id": 54,
    "alcohols":["tequila", "creme de cassis"],
    "name": "El Diablo",
    "ingredients": ["37 1/2 ml Tequila", "12 1/2 ml Crème de Cassis", "12 1/2 ml Lime Juice", "Ginger Beer"],
    "description": "Pour the tequila, cassis, and lime juice into a cocktail shaker filled with ice. Shake well. Strain into a Collins glass filled with ice. Top with ginger beer."},
    {"id": 55,
    "alcohols":["gin", "triple sec"],
    "name": "Breakfast Martini",
    "ingredients": ["45 ml Gin", "20 ml Triple Sec", "20 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "1 heaped spoon of Orange Marmalade", "flamed lemon zest"],
    "description": "Add the marmalade and the gin to the mixing tin. Stir until the marmalade dissolves, add the other ingredients and lots of ice. Shake well and fine strain over ice into a martini glass. Garnish with a flamed lemon zest."},
    {"id": 56,
    "alcohols":["vodka"],
    "name": "Caipivodka",
    "ingredients": ["50 ml Vodka", "1/2 Lime", "2 teaspoons Refined Sugar", "Lemon Slice"],
    "description": "Place lime and sugar into Old-Fashioned glass and muddle (mash the two ingredients together using a muddler or a wooden spoon). Fill the glass with crushed ice and add the vodka."},
    {"id": 57,
    "alcohols":["tequila", "triple sec"],
    "name": "Baja Gold",
    "ingredients": ["50 ml Tequila", "12 1/2 ml Triple Sec", "50 ml Pineapple Juice", "12 1/2 ml Lime Juice", "12 1/2 ml Simple Syrup", "Lime Wedge"],
    "description": "Chill a martini glass with ice and soda water. Add all ingredients into a mixing glass. Fill up mixing glass with cubed ice. Shake hard for 10 seconds. Double strain mixture into chilled martini glass. Garnish with lime wedge."},
    {"id": 58,
    "alcohols":["vodka", "peach schnapps"],
    "name": "Sex on the Beach",
    "ingredients": ["25 ml Vodka", "25 ml Peach Schnapps", "40 ml Orange Juice", "20 ml Cranberry Juice", "Orange Slice for Garnish"],
    "description": "Pour all ingredients into a cocktail shaker,Shake well, Pour into a highball glass filled with ice, Garnish with the orange slice."},
    {"id": 59,
    "alcohols":["tequila"],
    "name": "Tequila Sunrise",
    "ingredients": ["50 ml Tequila", "80 ml Orange Juice", "dash Grenadine Syrup", "Lime wedge", "Orange slice"],
    "description": "Add tequila into highball glass. Top up with ice. Add freshly squeezed orange juice , squeeze of lime and dash of grenadine syrup."},
    {"id": 60,
    "alcohols":["gin", "sweet red vermouth", "dry vermouth"],
    "name": "Bronx",
    "ingredients": ["50 ml Gin", "12 1/2 ml Sweet Red Vermouth", "12 1/2 ml Dry Vermouth", "25 ml Fresh Orange Juice", "Orange Zest Twist", "Maraschino Cherry"],
    "description": "Add all ingredients into a mixing glass filled with ice. Stir with a bar spoon to chill and dilute the drink. Strain into a cocktail glass. Zest the drink and glass with an orange twist and drop in the glass. Garnish with a maraschino cherry."},
    {"id": 61,
    "alcohols":["rum"],
    "name": "Caribbean Sunrise",
    "ingredients": ["45 ml Rum", "60 ml Orange Juice", "15 ml Grenadine Syrup", "Orange Slice"],
    "description": "Pour the rum and orange juice into glass over ice. Add the grenadine syrup, which will sink to the bottom. Do not stir. Garnish and serve."},
    {"id": 62,
    "alcohols":["gin", "dry vermouth"],
    "name": "Gibson",
    "ingredients": ["60 ml Gin", "10 ml Dry Vermouth", "1 Silverskin Onion"],
    "description": "Stir well in a shaker with ice, then strain into a chilled martini glass. Garnish with silverskin onion and serve."},
    {"id": 63,
    "alcohols":["vodka"],
    "name": "Bay Breeze",
    "ingredients": ["50 ml Vodka", "25 ml Pineapple Juice", "25 ml Cranberry Juice", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "Orange Wedge"],
    "description": "Add all ingredients in a cocktail shaker with ice and mix. Single strain drink into Tiki glass. Garnish with orange wedge."},
    {"id": 64,
    "alcohols":["rum", "raspberry liqueur"],
    "name": "Raspberry Mojito",
    "ingredients": ["50 ml White Rum", "15 ml Raspberry Liqueur", "25 ml Lime Juice", "35 ml Soda Water", "2 Bar Spoons Superfine Sugar", "5 Raspberries", "8 Mint Leaves"],
    "description": "Add all your ingredients into a tall glass with crushed ice and churn, to dissolve the sugar and chill the drink. Top up with crushed ice. Add straw and garnish with raspberry.Add all your ingredients into a tall glass with crushed ice and churn, to dissolve the sugar and chill the drink. Top up with crushed ice. Add straw and garnish with raspberry."},
    {"id": 65,
    "alcohols":["cognac", "triple sec"],
    "name": "SideCar",
    "ingredients": ["37 1/2 ml Cognac", "12 1/2 ml Triple Sec", "20 ml Lemon Juice", "dash Egg White", "5 ml Sugar Syrup", "Orange peel"],
    "description": "Chill a coupe glass with soda water. Add all the ingredients to a mixing tin and dry shake for 10 seconds. Add ice to the tin and shake vigorously for 10 seconds. Taste. Fine strain ingredients into chilled coupe glass. Zest orange peel into the drink and place orange twist into glass."},
    {"id": 66,
    "alcohols":["champagne", "brandy"],
    "name": "Champagne Cocktail",
    "ingredients": ["100 ml Champagne", "25 ml Brandy", "1 heaped bar spoon Sugar", "4 dashes Angostura Bitters"],
    "description": "Add 1 heaped bar spoon of sugar into a champagne glass. Add bitters and brandy. Churn with bar spoon to break down the sugar. Top off with champagne. Careful of the fizz!"},
    {"id": 67,
    "alcohols":["whiskey", "amaretto"],
    "name": "Godfather",
    "ingredients": ["37 1/2 ml Scotch Whiskey", "12 1/2 ml Amaretto"],
    "description": "Build the ingredients in an Old-Fashioned glass with ice cubes. Stir well and serve."},
    {"id": 68,
    "alcohols":["rum", "maraschino liqueur"],
    "name": "Hemingway Daiquiri",
    "ingredients": ["50 ml White Rum", "10 ml Maraschino Liqueur", "12 1/2 ml Grapefruit Juice", "12 1/2 ml Lime Juice", "12 1/2 ml Simple Syrup", "Maraschino Cherry"],
    "description": "Pour the ingredients into a cocktail shaker with ice cubes. Shake well. Double strain into a chilled martini glass. Garnish with a maraschino cherry"},
    {"id": 69,
    "alcohols":["rum"],
    "name": "Raspberry Daiquiri",
    "ingredients": ["50 ml Light Rum", "25 ml Lime Juice", "2 spoons Caster Sugar", "6 Raspberries"],
    "description": "Add 5 raspberries and sugar into mixing glass. Muddle down both ingredients into a paste. Add other 2 ingredients and fill the mixing glass with cubed ice. Shake for 10 – 15 seconds. Double strain drink into a coupe glass. Garnish with a raspberry."},
    {"id": 70,
    "alcohols":["gin"],
    "name": "Blueberry Collins",
    "ingredients": ["50 ml Gin", "25 ml Lemon Juice", "12 1/2 ml Vanilla Sugar Syrup", "19 Blueberries", "Top-Up Soda water"],
    "description": "Add the blueberries to the mixing tin and muddle with gin. Add the lemon juice, sugar syrup and lots of ice. Shake well, fine strain over ice and top up with Soda Water. Garnish with 3 blueberries."},
    {"id": 71,
    "alcohols":["gin"],
    "name": "Gimlet",
    "ingredients": ["60 ml Premium Gin", "10 ml Lime Cordial"],
    "description": "Add gin and lime cordial to a mixing glass filled with ice. Stir to dilute and chill the drink. Strain into a cocktail glass and serve straight up."},
    {"id": 72,
    "alcohols":["baileys", "coffee liqueur"],
    "name": "Chocolate-covered Cherry",
    "ingredients": ["30 ml Baileys Cream Liqueur", "30 ml Coffee Liqueur", "1 Tablespoon Grenadine Syrup"],
    "description": "Pre-measure your ingredients into separate shot glasses. Pour the grenadine into a rocks glass first. Slowly pour the coffee liqueur into the glass over the back of a spoon, being careful to let it run down the inside.Following the pouring instructions in step three, add the Baileys.Serve immediately, being careful not to rock the drink too much to avoid mixing the ingredients."},
    {"id": 73,
    "alcohols":["vodka"],
    "name": "Lemongrad",
    "ingredients": ["50 ml Citron Vodka", "25 ml Lemon Juice", "12 1/2 ml Elderflower Cordial", "Top-Up Tonic Water", "Pink Grapefruit Wedge"],
    "description": "Add the first three ingredients to the mixing tin with lots of ice, shake thoroughly, strain into highball glass over lots of ice and top up with tonic water. Garnish with pink grapefruit wedge."},
    {"id": 74,
    "alcohols":["rum"],
    "name": "Planters Punch",
    "ingredients": ["50 ml Dark Rum", "30 ml Lime Juice", "10 ml Grenadine Syrup", "15 ml Sugar Syrup", "Splash of Soda Water", "2 dashes Angostura Bitters"],
    "description": "Pour all ingredients into shaker filled with ice. Shake well. Pour into highball with ice. Top up with soda water. Stir gently and add a dash of Angostura Bitters. Garnish with orange slices."},
    {"id": 75,
    "alcohols":["peach schnapps", "champagne"],
    "name": "Blushing Bride",
    "ingredients": ["25 ml Peach Schnapps", "100 ml Champagne", "25 ml Grenadine Syrup"],
    "description": "Pour the peach schnapps and grenadine syrup into a Champagne flute. Top-up with Champagne."},
    {"id": 76,
    "alcohols":["gin"],
    "name": "Gin Rickey",
    "ingredients": ["50 ml Gin", "25 ml Lime Juice", "12 1/2 ml Sugar Syrup", "Soda Water", "Lime wedge"],
    "description": "Add all ingredients into Boston mixing tin, except the soda water. Fill the tin with ice and shake for about 10 seconds. Strain into a highball glass filled with ice and top up with soda water. Garnish with a wedge of lime."},
    {"id": 77,
    "alcohols":["rum", "passoa"],
    "name": "Passion Fruit Daiquiri",
    "ingredients": ["25 ml Bacardi Rum", "25 ml Passoa", "25 ml Lime Juice", "12 1/2 ml Sugar Syrup", "1 Passion Fruit"],
    "description": "Add all ingredients into Boston shaker with lots of ice and shake for about 15 seconds. Shake and fine strain into a chilled martini glass and then garnish with passion fruit shell."},
    {"id": 78,
    "alcohols":["tequila"],
    "name": "Cantarito",
    "ingredients": ["37 1/2 ml Tequila", "12 1/2 ml Lime Juice", "12 1/2 ml Orange Juice", "12 1/2 ml Lemon Juice", "10 ml Grapefruit Soda", "Lemon, Lime & Orange wedges", "Salt"],
    "description": "Rim a Collins glass with salt. Fill the glass with ice and add the tequila and juices.Top it off with grapefruit soda. Garnish with fruit wedges."},
    {"id": 79,
    "alcohols":["brandy"],
    "name": "Brandy Collins",
    "ingredients": ["50 ml Brandy", "25 ml Squeezed Lemon Juice", "15 ml Sugar Syrup", "15 ml Soda Water", "Maraschino Cherry", "Lemon Slice"],
    "description": "Mix the brandy, lemon juice and sugar syrup in a tall glass with ice. Top up with soda water, garnish with a maraschino cherry and a lemon slice and serve."},
    {"id": 80,
    "alcohols":["rum"],
    "name": "Volcano",
    "ingredients": ["125 ml Golden Rum", "25 ml Dark Rum", "10 ml 151 Rum", "6 dashes Absinthe", "6 dashes Angostura Bitters", "50 ml Pink Grapefruit Juice", "50 ml Orange Juice", "50 ml Pineapple Juice", "50 ml Lime Juice", "25 ml Falernum", "50 ml Grenadine Syrup", "Cinnamon"],
    "description": "Add all ingredients (except 151 proof rum) into a large mixing glass filled with ice. Stir with a bar spoon for 15 seconds. Pour into a mixing bowl or a volcano bowl if you have one available. Top with crushed ice. Pout on 151 proof rum and set light. Sprinkle cinnamon over drink to garnish."},
    {"id": 81,
    "alcohols":["campari", "sweet vermouth"],
    "name": "Americano",
    "ingredients": ["25 ml Campari", "25 ml Sweet Vermouth", "dash of Soda Water", "Lemon Peel"],
    "description": "Begin by topping up long glass with cubed ice. Add both alcohols and top up with soda water. Stir with bar spoon to make sure ingredients are mixed properly. Garnish with a lemon zest and add 2 long straws."},
    {"id": 82,
    "alcohols":["vodka", "champagne"],
    "name": "Accomplice",
    "ingredients": ["50 ml Vodka", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "Champagne", "3 Strawberries"],
    "description": "Muddle 2 strawberries in a Boston Mixing Glass. Add vodka, simple syrup and lemon juice. Fill with ice and shake for 10 seconds. Double strain into a chilled martini glass. Top-up with Champagne and garnish the glass with a strawberry."},
    {"id": 83,
    "alcohols":["vodka", "black rasberry liqueur"],
    "name": "Berry Nice",
    "ingredients": ["50 ml Raspberry Vodka", "5 ml Black Raspberry Liqueur", "12 1/2 ml Lemon Juice", "8 Blackberries", "Top-Up Ginger Beer"],
    "description": "Add the blackberries and vodka to the mixing tin and muddle well. Add the liqueur and lemon juice and lots of ice and shake well. Fine strain into Collins glass over ice and top up with ginger beer."},
    {"id": 84,
    "alcohols":["rum", "champagne"],
    "name": "Mojito Royal",
    "ingredients": ["40 ml White Rum", "30 ml Lime Juice", "3 Mint Leaves", "2 teaspoons Sugar", "Splash of Champagne"],
    "description": "Muddle mint sprigs in a glass with sugar and lime juice. Add rum and top up with Champagne. Garnish with sprig of mint leaves. Serve with a straw."},
    {"id": 85,
    "alcohols":["gin"],
    "name": "Tom Collins",
    "ingredients": ["37 1/2 ml Gin", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "splash Soda Water"],
    "description": "Chill highball glass with soda. Add the three ingredients into a mixing tin and fill tin up with ice. Shake for 10 -15 seconds. Taste. Fill highball with ice. Single strain into highball glass. Top up with soda and add straw. Garnish with lemon wedge."},
    {"id": 86,
    "alcohols":["vodka", "creme de mure"],
    "name": "Blackberry Mule",
    "ingredients": ["37 1/2 ml Vodka", "20 ml Crème de Mure", "25 ml Lime Juice", "Top-Up Ginger Beer", "6 Blackberries", "Aromatic Bitters"],
    "description": "Add 5 blackberries and lime juice into mixing glass. Using a muddler press down the blackberries. Add vodka, creme de mure and dash of aromatic bitters. Add cubed ice and stir with a bar spoon, making sure to get to bottom of glass. Top up with ginger beer and give another stir. Top up with cubed ice, add a straw and garnish with blackberry."},
    {"id": 87,
    "alcohols":["amaretto", "coffee liqueur"],
    "name": "Toasted Almond",
    "ingredients": ["37 1/2 ml Amaretto", "37 1/2 ml Coffee Liqueur", "25 ml Cream"],
    "description": "Pour the ingredients into a cocktail shaker with ice. Shake well. Strain into ice filled Old-Fashioned glass."},
    {"id": 88,
    "alcohols":["bourbon"],
    "name": "Boston Sour",
    "ingredients": ["50 ml Bourbon Whiskey", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "12 1/2 ml Egg-White", "Lemon Zest"],
    "description": "Put all ingredients into Boston shaker with ice. Prep your lemon zest garnish. Shake hard for about 15 seconds. Strain with a Hawthorne strainer into ice-filled Rocks glass. Zest the drink and the glass using the lemon zest."},
    {"id": 89,
    "alcohols":["vodka", "triple sec", "black raspberry liqueur"],
    "name": "Detropolitan",
    "ingredients": ["25 ml Vodka", "12 1/2 ml Triple Sec", "5 ml Black Raspberry Liqueur", "37 1/2 ml Cranberry Juice", "12 1/2 ml Lime Juice"],
    "description": "Add all the ingredients to the mixing tin, add lots of ice, shake thoroughly and strain into a chilled martini glass. Garnish with flamed orange zest."},
    {"id": 90,
    "alcohols":["gin", "chartreuse"],
    "name": "Alaska Cocktail",
    "ingredients": ["37 1/2 ml Gin", "20 ml Yellow Chartreuse", "3 drops Orange Bitters", "Orange Zest Twist"],
    "description": "Add all ingredients into a mixing glass filled with ice. Stir with a bar spoon to dilute and chill the drink. Pour into a cocktail glass and zest the drink and the glass using an orange zest twist. Serve straight up."},
    {"id": 91,
    "alcohols":["blue WKD"],
    "name": "Cheeky Vimto",
    "ingredients": ["275 ml Blue WKD", "50 ml Port"],
    "description": "Mix both ingredients with ice in a pub glass."},
    {"id": 92,
    "alcohols":["amaretto"],
    "name": "Amaretto Sunrise",
    "ingredients": ["45 ml Amaretto", "90 ml Orange Juice", "15 ml Grenadine Syrup", "Orange Slice"],
    "description": "Pour the amaretto and orange juice into glass over ice. Add the grenadine syrup, which will sink to the bottom. Do not stir. Garnish and serve."},
    {"id": 93,
    "alcohols":["vodka", "black raspberry liqueur"],
    "name": "Ballet Ruse",
    "ingredients": ["50 ml Vodka", "20 ml Black Raspberry Liqueur", "25 ml Lime Juice", "12 1/2 ml Sugar Syrup"],
    "description": "Add all the ingredients to the mixing tin, add lots of ice, shake thoroughly for 10 – 15 seconds and strain into a chilled martini glass."},
    {"id": 94,
    "alcohols":["rum", "triple sec"],
    "name": "Beachcomber",
    "ingredients": ["37 1/2 ml Light Rum", "12 1/2 ml Triple Sec", "1 dash Maraschino Liqueur", "12 1/2 ml Lime Juice"],
    "description": "Pour the ingredients into a cocktail shaker with ice cubes. Shake well for 20 seconds. Strain into a chilled cocktail glass."},
    {"id": 95,
    "alcohols":["vodka", "coffee liqueur", "irish cream liqueur"],
    "name": "Blind Russian",
    "ingredients": ["50 ml Vodka", "20 ml Coffee Liqueur", "30 ml Irish Cream Liqueur"],
    "description": "Pour coffee liqueur and vodka into an Old-Fashioned glass filled with ice. Float Irish cream liqueur on top and stir slowly."},
    {"id": 96,
    "alcohols":["melon liqueur"],
    "name": "Midori Sour",
    "ingredients": ["25 ml Melon Liqueur", "25 ml Sweet and Sour mix", "50 ml Lemon and Lime Soda"],
    "description": "Fill a tumbler with ice. Add the melon liqueur, sour mix, and lemon and lime soda, give a quick stir."},
    {"id": 97,
    "alcohols":["whiskey"],
    "name": "Donald Sutherland",
    "ingredients": ["45 ml Rye Whiskey", "25 ml Drambuie"],
    "description": "First fill a 650 ml glass with crushed ice until it is overflowing. Pour in Drambuie and rye whiskey. Stir gently, as to not bruise the ice. Keep stirring until a thick frost develops on the side of the glass. Garnish with a lemon twist. Serve."},
    {"id": 98,
    "alcohols":["gin"],
    "name": "Southside",
    "ingredients": ["50 ml Gin", "25 ml Lime Juice", "35 ml Soda Water", "2 dashes Grapefruit Bitters", "2 Bar Spoons Superfine Sugar", "6 Mint Leaves"],
    "description": "Add ingredients to a tall glass and stir to begin dissolving the sugar. Add crushed ice and muddle with a bar spoon. Top up with crushed ice, add 2 straws and garnish with mint."},
    {"id": 99,
    "alcohols":["rum"],
    "name": "Wahine",
    "ingredients": ["37 1/2 ml Light Rum", "25 ml Vodka", "37 1/2 ml Pineapple Juice", "25 ml Lemon Juice", "12 1/2 ml Sugar Syrup", "Mint Sprig"],
    "description": "Add all the ingredients to the mixing tin, add lots of ice, shake thoroughly for 10 seconds. Strain into rocks glass and garnish with fresh mint sprig."},
]